### ISSUE TITLE
JS IS WORKING!!!

### ISSUE THREAD

**Issue by CaptainCorin100** [CaptainCorin100/Prequel#3]
Discord is a text and voice software which we can use to talk in the week. It is free to make an account and to join a Prequel server follow this link: https://discord.gg/JveDmwd

**Comment by CaptainCorin100** [comment]
@aski6 the JS thing is working!!!!!! Now the list can grow in length. Pull changes!

**Comment by aski6** [comment]
is js working? I have started the server on a dev machine, and setup a url for statistics.html, I do not have any interactive ability, and my js blocker is set to allow.

**Comment by aski6** [comment]
found issue. on server, the url is a lower level than the static folder, so it is looking for static/jsfile in the new, lower "directory"

**Comment by aski6** [comment]
fixed issue temporaraly, however may have found a problem with a part of the form construction, discuss tommorow?

**Comment by CaptainCorin100** [comment]
ok

**Comment by CaptainCorin100** [comment]
the js works when I test it with the actual HTML page, but it may not work on python/linux?
