### ISSUE TITLE
Email Notifications?

### ISSUE THREAD

**Issue by CaptainCorin100** [CaptainCorin100/Prequel#4]
A mentor raised this issue- what would let people remember that they had to fill in their expenditures and net pay? Would email notifications be the way to go with that?
If so, does the sign up form require email?

**Comment by aski6** [comment]
Can setup database to include email, but adding email alerts to the program would be well beyond me to complete alongside the general site server-side. Should we keep a list of website features that should be added to a final version before real production use?

**Comment by CaptainCorin100** [comment]
ok
